services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chilembo-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - shared-services-network

networks:
  shared-services-network:
    external: true
    name: shared-services-network